SCREEN_TITLE = "Pyweek 31"

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 360

ROOM_WIDTH = 24 * 32
ROOM_HEIGHT = 24 * 18  # height is 16:9 ratio with width
SPAWN_RADIUS = 120
TILE_SPRITE_SCALING = 0.5
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SPRITE_SCALING


GRID_SIZE = 32

SPRITE_SCALING = 1

PLAYER_DEFAULT_START = (ROOM_WIDTH / 2, ROOM_HEIGHT / 2)

SPRITE_IMAGE_SIZE = 16
PARENT_DIR = ""

JETPACK = 1
GADGET_2 = 2
GADGET_3 = 3

MAXFUEL = 3
FUEL_REGENERATION_TIME = 120
JETPACK_BURST_LENGTH = 30
JETPACK_BURST_COOLDOWN = 70
JETPACK_DISTANCE_SCALE = 0.5
MAX_JETPACK_SPEED = 25

ANIMATION_SPEED = 2
